### ISSUE TITLE
Configure CI/CD

### ISSUE THREAD

**Issue by ja-chisholm** [UPEI-Android/group-project-mindjogg#4]
## Context
 There is currently no workflow or CI/CD set up.

## Problem
The application must be built and unit tests must be run automatically at certain intervals

## Solution:
- [x] Determine if CI/CD on Github is limited while using Github classroom
- [x] Set up a workflow under the "actions" tab on Github
- [x] In the yml file, set up jobs for package installation, linting, building, and testing (examples are given in the "actions" tab)
- [x] Depending on if CI/CD operations are limited, either set the yml file to run either at certain time intervals, or upon code being pushed.

**Comment by sontushkpaul** [comment]
@ja-chisholm is it still in progress?

**Comment by sontushkpaul** [comment]
@ja-chisholm can we add something like that: 

```
on:
  push:
    branches: [ dev, stage, main ]
  pull_request:
    branches: [ dev, stage, main ]
```
